로그아웃 기능을 구현하였습니다.
boostcampwm-2021/web09-Duxcord pull request #195
Opened 2021-11-12 11:37 UTC by shinhyogeun

## Related Issues

#194 
#169 
#93 
## What did you do?

- [x]  로그아웃 기능을 구현하였습니다.
- [x]  새로고침시 자신이 offline에 뜨는 버그를 수정하였습니다.

## 고민한 점, 질문거리

1. 로그 아웃 구현
로그아웃은 별도의 모달로 확인 후에 확인을 하면 로그아웃이 되도록 구현하였습니다. 모달에서 로그아웃을 누르면 백엔드로 logout요청을 보냅니다. 그 후 요청이 성공한다면 로그인 페이지로 이동한 후 현재 전역으로 관리되는 모든 state를 초기화하기위해 새로고침을 시도합니다. 따라서 API 요청 -> 새로 고침 식으로 진행됩니다.

2. 새로고침시 접속유저에 자신이 offline으로 뜨는 오류 수정
이 버그가 생긴 이유를 설명하겠습니다. 새로고침을 할 경우 소켓 연결을 끊고 다시 연결을 시도하는 과정이 있습니다. 이때 서버에 자신이 나간다는 것을 알리고 내가 나간것을 서버가 받아 다른 사람에게 알려줍니다.(정확하게는 자신의 속해있는 모든 그룹의 현재 접속 유저에게 뿌립니다.) 그후 자신이 다시 접속을 하면 똑같은 방식으로 자신이 속한 모든 그룹의 현재 접속인원에게 자신이 접속했다고 알립니다. 다만 자신이 offline으로 뜨는 이유는 자기 자신도 서버로 부터 접속 인원 배열을 받는데 거기에 자신이 속할때도 있고 안 속할 때도 있어서 그렇습니다. Group nav를 그리면서 1)자신이 들어왔다고 서버에 알립니다. 그리고 채팅부분을 그리면서 2)서버로부터 접속유저를 받아옵니다. 이 과정은 채팅페이지에서 새로고침을 하면 2가지 요청이 동시에 서버로 가게되고 1번과 2번의 실행순서가 보장이 되지 않아서 그렇습니다. 저는 그래서 실행순서를 보장하는 방법보다는 2번이 1번보다 먼저 실행될때는 자기 자신을 접속인원 배열에 넣어버리는 방식으로 고쳤습니다. 그 부분은 socket.ts의 다음 부분입니다.
```
 socket.on('GroupID', (groupID, user) => {
      if (user && !userConnectionInfo[groupID].map((v) => v.loginID).includes(user.loginID))
        userConnectionInfo[groupID] = [...userConnectionInfo[groupID], user];
      socket.emit('GroupUserConnection', userConnectionInfo[groupID]);
    });
```

2021-11-12 11:50 UTC, superLipbalm requested changes
고생하셨습니다! PR 내용이 자세해서 코드를 이해하기 수월했습니다!

2021-11-12 11:50 UTC, superLipbalm commented on server/src/socket.ts
> +      if (user && !userConnectionInfo[groupID].map((v) => v.loginID).includes(user.loginID))
```suggestion
      if (user && !userConnectionInfo[groupID].some((v) => v.loginID === user.loginID))
```
map().includes() 대신 some 메서드를 사용하면 더 간단하게 체크할 수 있습니다!

### 참고
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/some

2021-11-12 11:50 UTC, superLipbalm commented on client/src/redux/groupConnection/slice.ts
>        if (state.map((v: any) => v.loginID).includes(connection.loginID)) {
```suggestion
      if (state.some((v) => v.loginID === connection.loginID ) {
```
여기도 some메서드를 사용하는게 더 좋아보입니다~

2021-11-12 11:50 UTC, superLipbalm commented on client/src/components/Chat/index.tsx
> +  console.log(chats);
콘솔 지워주세요~

2021-11-12 11:53 UTC, shinhyogeun commented on client/src/components/Chat/index.tsx
> +  console.log(chats);
어멋.. 죄송합니다!!

2021-11-12 13:19 UTC, shinhyogeun commented
리뷰 감사합니다~! 반영해서 고쳐보았습니다~! 확인해주시면 감사하겠습니다!

2021-11-12 13:31 UTC, superLipbalm approved these changes

2021-11-13 15:50 UTC, SeojinSeojin approved these changes

2021-11-14 03:11 UTC, merged