Feat/그룹 삭제
boostcampwm-2021/web09-Duxcord pull request #230
Opened 2021-11-15 10:46 UTC by Najeong-Kim

## Related Issues

#211 

## What did you do?

- [ ]  그룹 삭제 API 구현
- [ ] 사용자가 해당 그룹의 리더가 아닌 경우 그룹 삭제 버튼 숨김
- [ ] 그룹 삭제 모달 생성
- [ ] 접속중인 그룹이 삭제될 경우 main으로 이동하도록 구현

![Nov-15-2021 19-45-16](https://user-images.githubusercontent.com/73640737/141768393-3977e2c6-8ec5-43b6-8392-739c3bcd6763.gif)

## 고민한 점, 질문거리

1. server의 socket.loader.ts 파일 47번째 줄에 socket.leave(code); 이 부분이 꼭 필요한가요!?? 없어도 오류는 안나는데 나가게 해줘야될 것 같아서 넣었어요
2. isLeader를 useState에 넣으니까 맨 처음에 깜빡여요ㅠ

버그를 발견한다면 언제든 알려주세요 ㅎㅎ

## 레퍼런스

2021-11-15 10:48 UTC, shinhyogeun commented
서버측의 소켓관리 객체를 정리하는 부분이 없는 것 같습니다~! 그 부분도 추가해주시면 좋을 것 같아요!

2021-11-15 11:43 UTC, Najeong-Kim commented
> 서버측의 소켓관리 객체를 정리하는 부분이 없는 것 같습니다~! 그 부분도 추가해주시면 좋을 것 같아요!

사용자 목록에서 삭제된 그룹을 제거했습니다!

2021-11-15 11:44 UTC, Najeong-Kim commented
오류가 자꾸 나는데 똑같이 해봐도 될 때도 있고 안될 때도 있습니다 휴............................이거는 같이 생각해봐야될 것 같아요 ㅠㅠ!

2021-11-16 02:20 UTC, SeojinSeojin approved these changes
수고많으셨습니다!! 에러는 하나도 안 납니다!!
리뷰 조금만 반영해주시면 좋을 것 같아요!!

2021-11-16 02:20 UTC, SeojinSeojin commented on server/src/controllers/group.controller.ts
> +  const userID = req.session.userID;
```suggestion
  const { userID } = req.session;
```
다른 곳에서 이런 식으로 많이 받아가지고!! 추천해봅니다

2021-11-16 02:20 UTC, SeojinSeojin commented on client/src/components/Modal/GroupDelete/index.tsx
> +
이 친구는 하는 일이 hide() 호출밖에 없으니 밑에 controller에서 그대로 내려줘도 괜찮을 것 같아!

2021-11-16 02:38 UTC, superLipbalm requested changes
고생하셨습니다!

2021-11-16 02:38 UTC, superLipbalm commented on client/src/components/SideBar/GroupSetting/index.tsx
> +  const [isLeader, setIsLeader] = useState(false);
```suggestion
  const isLeader = selectedGroup?.leader?.loginID === userdata?.loginID;
```
이거는 상수로 관리해도 될 것 같음!

2021-11-16 02:38 UTC, superLipbalm commented on client/src/components/SideBar/GroupSetting/index.tsx
> +  useEffect(() => {
```suggestion
  useLayoutEffect(() => {
```
계속 useState를 사용할꺼라면 여기를 useLayoutEffect로 바꾸면 안깜빡일것!

2021-11-16 02:43 UTC, shinhyogeun approved these changes

2021-11-16 02:54 UTC, superLipbalm approved these changes

2021-11-16 02:54 UTC, merged